
FutMapExchange = {
    "SP": ["SHFE", "纸浆"],
    "WR": ["SHFE", "线材"],
    "AU": ["SHFE", "黄金"],
    "BU": ["SHFE", "石油沥青"],
    "FU": ["SHFE", "燃料油"],
    "AG": ["SHFE", "沪银"],
    "AL": ["SHFE", "沪铝"],
    "CU": ["SHFE", "沪铜"],
    "HC": ["SHFE", "热压卷板"],
    "NI": ["SHFE", "沪镍"],
    "PB": ["SHFE", "沪铅"],
    "RB": ["SHFE", "螺纹钢"],
    "RU": ["SHFE", "橡胶"],
    "SN": ["SHFE", "沪锡"],
    "ZN": ["SHFE", "沪锌"],

    "A": ["DCE", "豆一"],
    "EG": ["DCE", "乙二醇"],
    "BB": ["DCE", "胶合板"],
    "JD": ["DCE", "鸡蛋"],
    "B": ["DCE", "豆二"],
    "C": ["DCE", "玉米"],
    "CS": ["DCE", "玉米淀粉"],
    "FB": ["DCE", "纤维板"],
    "I": ["DCE", "铁矿石"],
    "J": ["DCE", "焦炭"],
    "JM": ["DCE", "焦煤"],
    "L": ["DCE", "塑料"],
    "M": ["DCE", "豆粕"],
    "P": ["DCE", "棕榈油"],
    "PP": ["DCE", "聚丙烯"],
    "V": ["DCE", "PVC聚氯乙烯"],
    "Y": ["DCE", "豆油"],

    "AP": ["CZCE", "苹果"],
    "CJ": ["CZCE", "红枣"],
    "CY": ["CZCE", "棉纱"],
    "PM": ["CZCE", "普麦"],
    "RS": ["CZCE", "菜籽"],
    "SR": ["CZCE", "白糖"],
    "LR": ["CZCE", "晚籼粳"],
    "RM": ["CZCE", "菜粕"],
    "CF": ["CZCE", "郑棉"],
    "FG": ["CZCE", "玻璃"],
    "JR": ["CZCE", "粳稻"],
    "MA": ["CZCE", "甲醇"],
    "OI": ["CZCE", "菜油"],
    "RI": ["CZCE", "早籼稻"],
    "SF": ["CZCE", "硅铁"],
    "SM": ["CZCE", "锰硅"],
    "TA": ["CZCE", "PTA精对苯二甲酸"],    # 生产聚酯纤维
    "WH": ["CZCE", "强麦"],
    "ZC": ["CZCE", "动力煤"]
}