#logging:
#  level:
#    ROOT: DEBUG
#    org.springframework.cloud.gateway: DEBUG
server:
  port: 8888
eureka:
  client:
     #下面两项没有代码提示
     serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    globalcors:
      add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
      cors-configurations:
        '[/**]':
          allowedCredentials: true
          allowedOrigins: "*"
          allowedHeaders: "*"
          allowedMethods: "*"
      gateway:
        routes:
          - id: bulletscreen
            uri: lb://bullet
            predicates:
              - Path=/bullet/**
#          - id: bulletscreen
#            uri: lb:ws://bullet
#            predicates:
#              - Path=/bullet/**
          - id: producer
            uri: lb://eureka-producer
            predicates:
              - Path=/eureka-producer/**
#      routes:
#        - id: RegisterLogin
#          #          uri: http://localhost:8765/
#          uri: lb://RegisterLogin
#          predicates:
#            - Path=/**
#          filters:
#            #          - StripPrefix=1
#            - Auth=true


management:
  endpoints:
    web:
      exposure:
        include: refresh
