#logging:
#  level:
#    ROOT: DEBUG
#    org.springframework.cloud.gateway: DEBUG
server:
  port: 8888
eureka:
  client:
     #下面两项没有代码提示
     serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      routes:
      - id: bulletscreen
        uri: lb://bullet
        predicates:
        - Path=/bullet/**
      - id: bulletscreen
        uri: lb:ws://bullet
        predicates:
        - Path=/bullet/**
      - id: producer
        uri: http://localhost:8765
        predicates:
        - Path=/eureka-producer/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600


#        filters:
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/incaseoffailureusethis
#        - RewritePath=/consumingserviceendpoint, /backingserviceendpoint
management:
  endpoints:
    web:
      exposure:
        include: refresh
