server:
  port: 8888

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true   # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            maxAge: 360000
      routes:
#        - id: bullet
#          uri: lb://bullet
#          predicates:
#            - Path=/bullet/**
#          filters:
#            - CorsFilter=true
#        - id: bulletscreen
#          uri: lb:ws://bullet
#          predicates:
#            - Path=/bullet/**
#          filters:
#            - CorsFilter=true
        - id: eureka-producer
          uri: lb://eureka-producer
          predicates:
            - Path=/eureka-producer/**
          filters:
            - CorsFilter=true
#          filters:
#            - AccessControlAllowOriginFilter=true

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    #下面两项没有代码提示
    serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:8761/eureka/
