server:
  port: 8888

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            maxAge: 3600
#        add-to-simple-url-handler-mapping: true   # 解决options请求被拦截问题
      routes:
        - id: bullet
          uri: lb://agent-bullet
          predicates:
            - Path=/agent-bullet/**
        - id: bulletscreen
          uri: lb:ws://agent-bullet
          predicates:
            - Path=/agent-bullet/**
        - id: agent-producer
          uri: lb://agent-producer
          predicates:
            - Path=/**
# 以上通过postman可以跑通，但未解决options请求问题
#          filters:
#            - Cors=true

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    #下面两项没有代码提示
    serviceUrl:
      #服务治理地址
      defaultZone: http://localhost:8761/eureka/
